// Copyright (C) 2024-2026 Tristan Stoltz / Luminous Dynamics
// SPDX-License-Identifier: AGPL-3.0-or-later
//! Geometric Dilution of Precision (GDOP/PDOP) analysis.
//!
//! GDOP measures how anchor geometry affects position accuracy.
//! Low GDOP (< 3) = well-distributed anchors = good accuracy.
//! High GDOP (> 10) = clustered/collinear anchors = poor accuracy.

use serde::{Deserialize, Serialize};

/// Maximum number of points generated by one checked coverage-grid request.
pub const MAX_COVERAGE_GRID_POINTS: usize = 1_000_000;

/// Errors that make a coverage-grid request unsafe or ill-defined.
#[derive(Debug, Clone, PartialEq)]
pub enum CoverageGridError {
    NonFiniteInput { field: &'static str },
    NonPositiveStep { step: f64 },
    ReversedRange {
        axis: &'static str,
        start: f64,
        end: f64,
    },
    NonFiniteAnchor {
        anchor_index: usize,
        component: usize,
    },
    TooManyPoints { requested: u64, max: usize },
}

impl std::fmt::Display for CoverageGridError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::NonFiniteInput { field } => write!(f, "{field} must be finite"),
            Self::NonPositiveStep { step } => {
                write!(f, "coverage-grid step must be positive, got {step}")
            }
            Self::ReversedRange { axis, start, end } => {
                write!(f, "{axis} range must satisfy start <= end, got {start}..={end}")
            }
            Self::NonFiniteAnchor {
                anchor_index,
                component,
            } => write!(
                f,
                "anchor {anchor_index} component {component} must be finite"
            ),
            Self::TooManyPoints { requested, max } => {
                write!(f, "coverage grid requests {requested} points; maximum is {max}")
            }
        }
    }
}

impl std::error::Error for CoverageGridError {}

/// A coverage analysis point.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CoveragePoint {
    pub x: f64,
    pub y: f64,
    pub z: f64,
    pub gdop: f64,
    pub pdop: f64,
}

/// Compute GDOP (Geometric Dilution of Precision) at a point.
///
/// GDOP = sqrt(trace((J^T J)^-1)) where J is the geometry matrix.
/// Lower is better. Returns f64::INFINITY for degenerate or invalid geometry.
///
/// # Arguments
/// - `anchors`: Known anchor positions (body-fixed Cartesian, meters)
/// - `point`: Query position (where we want to know the accuracy)
pub fn gdop(anchors: &[[f64; 3]], point: &[f64; 3]) -> f64 {
    if anchors.len() < 4
        || point.iter().any(|v| !v.is_finite())
        || anchors.iter().flatten().any(|v| !v.is_finite())
    {
        return f64::INFINITY;
    }

    // Build geometry matrix J: each row is unit vector from point to anchor
    let mut jtj = [[0.0_f64; 3]; 3];
    for anchor in anchors {
        let dx = anchor[0] - point[0];
        let dy = anchor[1] - point[1];
        let dz = anchor[2] - point[2];
        let dist = (dx * dx + dy * dy + dz * dz).sqrt();
        if dist < 1e-10 {
            continue;
        }
        let u = [dx / dist, dy / dist, dz / dist];

        for a in 0..3 {
            for b in 0..3 {
                jtj[a][b] += u[a] * u[b];
            }
        }
    }

    // GDOP = sqrt(trace(inv(J^T J)))
    match invert_3x3(&jtj) {
        Some(inv) => {
            let trace = inv[0][0] + inv[1][1] + inv[2][2];
            if trace > 0.0 && trace.is_finite() {
                trace.sqrt()
            } else {
                f64::INFINITY
            }
        }
        None => f64::INFINITY,
    }
}

/// Compute PDOP (Position Dilution of Precision) — same as GDOP for 3D.
/// Included for API clarity; in our formulation PDOP = GDOP.
pub fn pdop(anchors: &[[f64; 3]], point: &[f64; 3]) -> f64 {
    gdop(anchors, point)
}

/// Compute 2D GDOP (horizontal dilution) at a surface point.
pub fn gdop_2d(anchors: &[[f64; 2]], point: &[f64; 2]) -> f64 {
    if anchors.len() < 3
        || point.iter().any(|v| !v.is_finite())
        || anchors.iter().flatten().any(|v| !v.is_finite())
    {
        return f64::INFINITY;
    }

    let mut jtj = [[0.0_f64; 2]; 2];
    for anchor in anchors {
        let dx = anchor[0] - point[0];
        let dy = anchor[1] - point[1];
        let dist = (dx * dx + dy * dy).sqrt();
        if dist < 1e-10 {
            continue;
        }
        let u = [dx / dist, dy / dist];
        for a in 0..2 {
            for b in 0..2 {
                jtj[a][b] += u[a] * u[b];
            }
        }
    }

    let det = jtj[0][0] * jtj[1][1] - jtj[0][1] * jtj[1][0];
    if !det.is_finite() || det.abs() < 1e-20 {
        return f64::INFINITY;
    }
    let trace_inv = (jtj[1][1] + jtj[0][0]) / det;
    if trace_inv > 0.0 && trace_inv.is_finite() {
        trace_inv.sqrt()
    } else {
        f64::INFINITY
    }
}

fn checked_grid_axis_count(
    axis: &'static str,
    range: (f64, f64),
    step: f64,
) -> Result<usize, CoverageGridError> {
    if !range.0.is_finite() || !range.1.is_finite() {
        return Err(CoverageGridError::NonFiniteInput { field: axis });
    }
    if range.0 > range.1 {
        return Err(CoverageGridError::ReversedRange {
            axis,
            start: range.0,
            end: range.1,
        });
    }

    let intervals = ((range.1 - range.0) / step).floor();
    if !intervals.is_finite() || intervals < 0.0 {
        return Err(CoverageGridError::NonFiniteInput { field: axis });
    }

    let count = intervals + 1.0;
    if count > MAX_COVERAGE_GRID_POINTS as f64 {
        return Err(CoverageGridError::TooManyPoints {
            requested: count.min(u64::MAX as f64) as u64,
            max: MAX_COVERAGE_GRID_POINTS,
        });
    }
    Ok(count as usize)
}

/// Evaluate coverage quality over a bounded grid of points.
///
/// This is the authority-facing form. It rejects non-finite/reversed ranges,
/// non-positive or non-finite steps, non-finite anchors, and requests that
/// would allocate more than [`MAX_COVERAGE_GRID_POINTS`]. Iteration uses
/// pre-qualified integer counts rather than open-ended floating-point loops.
pub fn coverage_grid_2d_checked(
    anchors: &[[f64; 2]],
    x_range: (f64, f64),
    y_range: (f64, f64),
    step: f64,
) -> Result<Vec<CoveragePoint>, CoverageGridError> {
    if !step.is_finite() {
        return Err(CoverageGridError::NonFiniteInput { field: "step" });
    }
    if step <= 0.0 {
        return Err(CoverageGridError::NonPositiveStep { step });
    }
    for (anchor_index, anchor) in anchors.iter().enumerate() {
        for (component, value) in anchor.iter().enumerate() {
            if !value.is_finite() {
                return Err(CoverageGridError::NonFiniteAnchor {
                    anchor_index,
                    component,
                });
            }
        }
    }

    let x_count = checked_grid_axis_count("x_range", x_range, step)?;
    let y_count = checked_grid_axis_count("y_range", y_range, step)?;
    let requested = x_count
        .checked_mul(y_count)
        .ok_or(CoverageGridError::TooManyPoints {
            requested: u64::MAX,
            max: MAX_COVERAGE_GRID_POINTS,
        })?;
    if requested > MAX_COVERAGE_GRID_POINTS {
        return Err(CoverageGridError::TooManyPoints {
            requested: requested.min(u64::MAX as usize) as u64,
            max: MAX_COVERAGE_GRID_POINTS,
        });
    }

    let mut points = Vec::with_capacity(requested);
    for x_index in 0..x_count {
        let x = x_range.0 + x_index as f64 * step;
        for y_index in 0..y_count {
            let y = y_range.0 + y_index as f64 * step;
            let g = gdop_2d(anchors, &[x, y]);
            points.push(CoveragePoint {
                x,
                y,
                z: 0.0,
                gdop: g,
                pdop: g,
            });
        }
    }
    Ok(points)
}

/// Backward-compatible coverage-grid helper.
///
/// Invalid or unbounded requests now fail closed to an empty grid rather than
/// entering a non-terminating loop or attempting an excessive allocation.
/// New authority-facing callers should use [`coverage_grid_2d_checked`] so the
/// rejection reason remains observable.
pub fn coverage_grid_2d(
    anchors: &[[f64; 2]],
    x_range: (f64, f64),
    y_range: (f64, f64),
    step: f64,
) -> Vec<CoveragePoint> {
    coverage_grid_2d_checked(anchors, x_range, y_range, step).unwrap_or_default()
}

fn invert_3x3(m: &[[f64; 3]; 3]) -> Option<[[f64; 3]; 3]> {
    let det = m[0][0] * (m[1][1] * m[2][2] - m[1][2] * m[2][1])
        - m[0][1] * (m[1][0] * m[2][2] - m[1][2] * m[2][0])
        + m[0][2] * (m[1][0] * m[2][1] - m[1][1] * m[2][0]);
    if !det.is_finite() || det.abs() < 1e-30 {
        return None;
    }
    let d = 1.0 / det;
    Some([
        [
            (m[1][1] * m[2][2] - m[1][2] * m[2][1]) * d,
            (m[0][2] * m[2][1] - m[0][1] * m[2][2]) * d,
            (m[0][1] * m[1][2] - m[0][2] * m[1][1]) * d,
        ],
        [
            (m[1][2] * m[2][0] - m[1][0] * m[2][2]) * d,
            (m[0][0] * m[2][2] - m[0][2] * m[2][0]) * d,
            (m[0][2] * m[1][0] - m[0][0] * m[1][2]) * d,
        ],
        [
            (m[1][0] * m[2][1] - m[1][1] * m[2][0]) * d,
            (m[0][1] * m[2][0] - m[0][0] * m[2][1]) * d,
            (m[0][0] * m[1][1] - m[0][1] * m[1][0]) * d,
        ],
    ])
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn gdop_well_distributed() {
        let anchors = [
            [100.0, 0.0, 0.0],
            [-50.0, 86.6, 0.0],
            [-50.0, -86.6, 0.0],
            [0.0, 0.0, 100.0],
        ];
        let g = gdop(&anchors, &[0.0, 0.0, 0.0]);
        assert!(g < 3.0, "GDOP {} should be < 3 for good geometry", g);
    }

    #[test]
    fn gdop_collinear_is_high() {
        let anchors = [
            [100.0, 0.0, 0.0],
            [200.0, 0.0, 0.0],
            [300.0, 0.0, 0.0],
            [400.0, 0.0, 0.0],
        ];
        let g = gdop(&anchors, &[0.0, 0.0, 0.0]);
        assert!(
            g > 10.0 || g.is_infinite(),
            "GDOP {} should be high for collinear",
            g
        );
    }

    #[test]
    fn gdop_insufficient_anchors() {
        let g = gdop(&[[1.0, 0.0, 0.0]], &[0.0, 0.0, 0.0]);
        assert!(g.is_infinite());
    }

    #[test]
    fn gdop_rejects_non_finite_geometry() {
        let anchors = [
            [0.0, 0.0, 0.0],
            [100.0, 0.0, 0.0],
            [0.0, 100.0, 0.0],
            [0.0, 0.0, f64::NAN],
        ];
        assert!(gdop(&anchors, &[1.0, 1.0, 1.0]).is_infinite());
    }

    #[test]
    fn gdop_2d_triangle() {
        let anchors = [[0.0, 0.0], [100.0, 0.0], [50.0, 86.6]];
        let g = gdop_2d(&anchors, &[50.0, 30.0]);
        assert!(
            g < 5.0,
            "2D GDOP {} should be reasonable for equilateral triangle",
            g
        );
    }

    #[test]
    fn coverage_grid_produces_points() {
        let anchors = [[0.0, 0.0], [100.0, 0.0], [50.0, 86.6]];
        let grid = coverage_grid_2d_checked(&anchors, (0.0, 100.0), (0.0, 100.0), 25.0)
            .expect("valid bounded grid");
        assert!(grid.len() > 10);
        let center = grid
            .iter()
            .find(|p| (p.x - 50.0).abs() < 13.0 && (p.y - 50.0).abs() < 13.0);
        assert!(center.is_some());
    }

    #[test]
    fn coverage_grid_rejects_non_positive_or_non_finite_step() {
        let anchors = [[0.0, 0.0], [100.0, 0.0], [50.0, 86.6]];
        assert!(coverage_grid_2d_checked(&anchors, (0.0, 1.0), (0.0, 1.0), 0.0).is_err());
        assert!(coverage_grid_2d_checked(&anchors, (0.0, 1.0), (0.0, 1.0), -1.0).is_err());
        assert!(coverage_grid_2d_checked(&anchors, (0.0, 1.0), (0.0, 1.0), f64::NAN).is_err());
        assert!(coverage_grid_2d_checked(&anchors, (0.0, 1.0), (0.0, 1.0), f64::INFINITY).is_err());
    }

    #[test]
    fn coverage_grid_rejects_reversed_or_non_finite_ranges() {
        let anchors = [[0.0, 0.0], [100.0, 0.0], [50.0, 86.6]];
        assert!(coverage_grid_2d_checked(&anchors, (2.0, 1.0), (0.0, 1.0), 0.1).is_err());
        assert!(coverage_grid_2d_checked(&anchors, (0.0, f64::NAN), (0.0, 1.0), 0.1).is_err());
    }

    #[test]
    fn coverage_grid_rejects_excessive_work() {
        let anchors = [[0.0, 0.0], [100.0, 0.0], [50.0, 86.6]];
        let err = coverage_grid_2d_checked(&anchors, (0.0, 10_000.0), (0.0, 10_000.0), 0.01)
            .expect_err("grid should be bounded");
        assert!(matches!(err, CoverageGridError::TooManyPoints { .. }));
    }

    #[test]
    fn legacy_coverage_grid_fails_closed_without_looping() {
        let anchors = [[0.0, 0.0], [100.0, 0.0], [50.0, 86.6]];
        let grid = coverage_grid_2d(&anchors, (0.0, 1.0), (0.0, 1.0), 0.0);
        assert!(grid.is_empty());
    }
}
