[package]
name = "hearth_care_transition_test_harness"
version = "0.1.0"
edition = "2024"
license = "AGPL-3.0-or-later"
publish = false

[lib]
crate-type = ["cdylib", "rlib"]
name = "hearth_care_transition_test_harness"

[dependencies]
hdk = "0.6.0"
hearth_care_integrity = { path = "../../../../zomes/hearth-care/integrity" }
hearth_kinship_integrity = { path = "../../../../zomes/hearth-kinship/integrity" }
hearth_care_transitions_integrity = { path = "../../../../zomes/hearth-care-transitions/integrity" }
hearth_care_transition_fake_integrity = { path = "../fake-integrity" }
