use std::{env, fs, path::PathBuf, sync::Arc};

use mycelix_content_core::{BlobDescriptorV1, DigestAlgorithmV1};
use mycelix_content_node::{CasConfigV1, LocalCasV1};
use mycelix_nix_cache::{serve, NixCacheCatalogV1, NixCacheConfigV1, NixCacheEntryV1};

const QUALIFICATION_QUOTA_BYTES: u64 = 64 * 1024 * 1024;

#[tokio::main]
async fn main() -> Result<(), Box<dyn std::error::Error>> {
    let mut args = env::args().skip(1);
    let cas_root = PathBuf::from(next_arg(&mut args, "CAS root")?);
    let port: u16 = next_arg(&mut args, "port")?.parse()?;
    let store_path = next_arg(&mut args, "store path")?;
    let nar_path = PathBuf::from(next_arg(&mut args, "NAR path")?);
    let signature = next_arg(&mut args, "Nix signature")?;
    if args.next().is_some() {
        return Err("unexpected extra qualification-server arguments".into());
    }

    let nar = fs::read(nar_path)?;
    let descriptor = BlobDescriptorV1::from_bytes(DigestAlgorithmV1::Sha256, &nar, None);
    let quota = QUALIFICATION_QUOTA_BYTES.max(descriptor.size_bytes.saturating_mul(2));
    let cas = LocalCasV1::open(CasConfigV1::new(&cas_root, quota))?;
    cas.put(&descriptor, nar.as_slice())?;

    // The stock-Nix qualification fixture deliberately has no runtime
    // references. Its signature is generated by Nix itself before this server
    // starts and is merely preserved by CF-07.
    let entry = NixCacheEntryV1::new(
        &store_path,
        descriptor.digest,
        descriptor.size_bytes,
        vec![],
        None,
        vec![signature.as_str()],
        None,
    )?;
    let catalog = NixCacheCatalogV1::new(vec![entry])?;

    eprintln!("CF-07 qualification server configured on 127.0.0.1:{port}");
    serve(
        Arc::new(cas),
        Arc::new(catalog),
        NixCacheConfigV1::loopback(port),
    )
    .await?;
    Ok(())
}

fn next_arg(
    args: &mut impl Iterator<Item = String>,
    name: &'static str,
) -> Result<String, Box<dyn std::error::Error>> {
    args.next()
        .ok_or_else(|| format!("missing qualification-server argument: {name}").into())
}
