// Copyright (C) 2024-2026 Tristan Stoltz / Luminous Dynamics
// SPDX-License-Identifier: AGPL-3.0-or-later
//! Pure exact attempt identity for one response effect.
//!
//! This crate intentionally separates three identities:
//!
//! 1. **effect identity** — what physical/logical effect is being attempted;
//! 2. **authority qualification identity** — which exact current executor and
//!    safety qualification prepared it; and
//! 3. **attempt identity** — one nonce/reference for one try at that effect.
//!
//! Effect identity deliberately excludes current authority generations and
//! dynamic verification times so an authority refresh cannot create a new effect
//! namespace and accidentally permit duplicate physical action.
//!
//! This is not durable reservation. The caller-supplied attempt nonce/reference
//! are only candidate attempt identity until a later trusted journal owns and
//! persists them before any effect.

use mycelix_authority_coordinator_stability_fence::{
    CoordinatorAdmissionSubject, PROTOCOL_VERSION as STABILITY_PROTOCOL_VERSION,
};
use mycelix_institutional_core::Digest32;
use mycelix_response_current_executor::QualifiedResponseCurrentExecutor;
use mycelix_response_effect_safety::QualifiedResponseEffectSafety;
use serde::Serialize;
use std::fmt;

pub const PROTOCOL_VERSION: &str = "mycelix-response-attempt-identity-v0.1";
pub const EFFECT_IDENTITY_PROFILE: &str =
    "mycelix-response-effect-identity-v1-blake3-framed";
pub const ATTEMPT_IDENTITY_PROFILE: &str =
    "mycelix-response-attempt-identity-v1-blake3-framed";
pub const EVIDENCE_PROFILE: &str =
    "mycelix-response-attempt-evidence-v1-blake3-framed";

const DOMAIN_EFFECT: &[u8] = b"mycelix/response/effect-identity/v1";
const DOMAIN_ATTEMPT: &[u8] = b"mycelix/response/attempt-identity/v1";
const DOMAIN_EVIDENCE: &[u8] = b"mycelix/response/attempt-evidence/v1";
const MAX_REF_BYTES: usize = 2048;

/// Non-deserializable prepared attempt identity.
///
/// It is suitable as the exact subject for #298 coordinator stability fencing,
/// but does not prove its nonce/reference were generated by a trusted runtime or
/// written durably.
#[derive(Clone, Debug, PartialEq, Eq, Serialize)]
pub struct PreparedResponseAttempt {
    proposal_id: String,
    proposal_digest: String,
    decision_id: String,
    option_id: String,
    action_class: String,
    actions_digest: Digest32,
    actions_digest_profile: String,
    adapter_profile: String,
    effect_identity_digest: Digest32,
    response_current_executor_digest: Digest32,
    response_safety_digest: Digest32,
    attempt_nonce: [u8; 32],
    attempt_ref: String,
    attempt_identity_digest: Digest32,
    coordinator_admission_subject: CoordinatorAdmissionSubject,
    automatic_effects_allowed: bool,
    max_attempt_lease_ms: u64,
    evidence_digest: Digest32,
    prepared_at_ms: u64,
    valid_until_ms: u64,
}

impl PreparedResponseAttempt {
    pub fn proposal_id(&self) -> &str {
        &self.proposal_id
    }

    pub fn proposal_digest(&self) -> &str {
        &self.proposal_digest
    }

    pub fn decision_id(&self) -> &str {
        &self.decision_id
    }

    pub fn option_id(&self) -> &str {
        &self.option_id
    }

    pub fn action_class(&self) -> &str {
        &self.action_class
    }

    pub fn actions_digest(&self) -> Digest32 {
        self.actions_digest
    }

    pub fn actions_digest_profile(&self) -> &str {
        &self.actions_digest_profile
    }

    pub fn adapter_profile(&self) -> &str {
        &self.adapter_profile
    }

    /// Stable physical/logical effect identity. Authority refreshes do not alter
    /// this key if the exact selected action remains unchanged.
    pub fn effect_identity_digest(&self) -> Digest32 {
        self.effect_identity_digest
    }

    pub fn effect_identity_profile(&self) -> &str {
        EFFECT_IDENTITY_PROFILE
    }

    pub fn response_current_executor_digest(&self) -> Digest32 {
        self.response_current_executor_digest
    }

    pub fn response_safety_digest(&self) -> Digest32 {
        self.response_safety_digest
    }

    pub fn attempt_nonce(&self) -> [u8; 32] {
        self.attempt_nonce
    }

    pub fn attempt_ref(&self) -> &str {
        &self.attempt_ref
    }

    pub fn attempt_identity_digest(&self) -> Digest32 {
        self.attempt_identity_digest
    }

    pub fn attempt_identity_profile(&self) -> &str {
        ATTEMPT_IDENTITY_PROFILE
    }

    pub fn coordinator_admission_subject(&self) -> &CoordinatorAdmissionSubject {
        &self.coordinator_admission_subject
    }

    pub fn automatic_effects_allowed(&self) -> bool {
        self.automatic_effects_allowed
    }

    pub fn max_attempt_lease_ms(&self) -> u64 {
        self.max_attempt_lease_ms
    }

    pub fn evidence_digest(&self) -> Digest32 {
        self.evidence_digest
    }

    pub fn evidence_profile(&self) -> &str {
        EVIDENCE_PROFILE
    }

    pub fn prepared_at_ms(&self) -> u64 {
        self.prepared_at_ms
    }

    pub fn valid_until_ms(&self) -> u64 {
        self.valid_until_ms
    }

    pub const fn exact_effect_identity_bound_here(&self) -> bool {
        true
    }

    pub const fn coordinator_admission_subject_bound_here(&self) -> bool {
        true
    }

    /// Pure preparation cannot establish who generated the nonce/reference.
    pub const fn attempt_identity_origin_verified_here(&self) -> bool {
        false
    }

    /// A later native journal must fsync the reservation before this becomes true.
    pub const fn durably_reserved_here(&self) -> bool {
        false
    }

    pub const fn coordinator_stability_fenced_here(&self) -> bool {
        false
    }

    pub const fn coordinator_update_excluded_here(&self) -> bool {
        false
    }

    pub const fn grants_execution_authority(&self) -> bool {
        false
    }
}

/// Prepare one exact attempt identity and its #298 admission subject.
///
/// `attempt_nonce` and `attempt_ref` are candidate identity only. A later native
/// durable store must own/generate or otherwise independently trust them and
/// persist the exact manifest before any effect-capable call.
pub fn prepare_response_attempt(
    current: &QualifiedResponseCurrentExecutor,
    safety: &QualifiedResponseEffectSafety,
    attempt_nonce: [u8; 32],
    attempt_ref: impl Into<String>,
    now_ms: u64,
) -> Result<PreparedResponseAttempt, ResponseAttemptIdentityError> {
    if now_ms == 0 {
        return Err(ResponseAttemptIdentityError::InvalidPreparationTime);
    }
    if attempt_nonce == [0u8; 32] {
        return Err(ResponseAttemptIdentityError::ZeroAttemptNonce);
    }
    let attempt_ref = attempt_ref.into();
    require_ref(&attempt_ref)?;

    if current.valid_until_ms() <= now_ms || safety.valid_until_ms() <= now_ms {
        return Err(ResponseAttemptIdentityError::UpstreamQualificationExpired);
    }
    if current.response_safety_qualification_digest() != safety.qualification_digest() {
        return Err(ResponseAttemptIdentityError::ResponseSafetyIdentityMismatch);
    }
    if !safety.all_declared_authority_subjects_satisfied() {
        return Err(ResponseAttemptIdentityError::PendingAuthoritySubjects);
    }

    require_exact_response_equality(current, safety)?;

    let effect_identity_digest = effect_identity(safety);
    let response_current_executor_digest = current.qualification_digest();
    let response_safety_digest = safety.qualification_digest();
    let attempt_identity_digest = attempt_identity(
        effect_identity_digest,
        response_current_executor_digest,
        response_safety_digest,
        &attempt_nonce,
        &attempt_ref,
    );

    // #298's subject binds the exact current response authority theorem plus a
    // separate attempt nonce/ref. The stable effect key remains a journal concern
    // and is also committed by our attempt identity.
    let coordinator_admission_subject = CoordinatorAdmissionSubject {
        protocol_version: STABILITY_PROTOCOL_VERSION.into(),
        subject_digest: current.qualification_digest().0,
        subject_profile: current.qualification_profile().into(),
        attempt_nonce,
        attempt_ref: attempt_ref.clone(),
    };
    coordinator_admission_subject
        .validate()
        .map_err(|error| ResponseAttemptIdentityError::CoordinatorSubject(error.to_string()))?;

    let max_attempt_lease_ms = safety.max_attempt_lease_ms();
    if max_attempt_lease_ms == 0 {
        return Err(ResponseAttemptIdentityError::ZeroAttemptLease);
    }
    let policy_horizon = now_ms
        .checked_add(max_attempt_lease_ms)
        .ok_or(ResponseAttemptIdentityError::AttemptLeaseOverflow)?;
    let valid_until_ms = current
        .valid_until_ms()
        .min(safety.valid_until_ms())
        .min(policy_horizon);
    if valid_until_ms <= now_ms {
        return Err(ResponseAttemptIdentityError::NoUsableAttemptWindow);
    }

    let evidence_digest = evidence_identity(
        attempt_identity_digest,
        current.evidence_digest(),
        safety.evidence_digest(),
        now_ms,
        valid_until_ms,
    );

    Ok(PreparedResponseAttempt {
        proposal_id: safety.proposal_id().into(),
        proposal_digest: safety.proposal_digest().into(),
        decision_id: safety.decision_id().into(),
        option_id: safety.option_id().into(),
        action_class: safety.action_class().into(),
        actions_digest: safety.actions_digest(),
        actions_digest_profile: safety.actions_digest_profile().into(),
        adapter_profile: safety.adapter_profile().into(),
        effect_identity_digest,
        response_current_executor_digest,
        response_safety_digest,
        attempt_nonce,
        attempt_ref,
        attempt_identity_digest,
        coordinator_admission_subject,
        automatic_effects_allowed: safety.automatic_effects_allowed(),
        max_attempt_lease_ms,
        evidence_digest,
        prepared_at_ms: now_ms,
        valid_until_ms,
    })
}

fn require_exact_response_equality(
    current: &QualifiedResponseCurrentExecutor,
    safety: &QualifiedResponseEffectSafety,
) -> Result<(), ResponseAttemptIdentityError> {
    if current.proposal_id() != safety.proposal_id()
        || current.proposal_digest() != safety.proposal_digest()
        || current.decision_id() != safety.decision_id()
        || current.option_id() != safety.option_id()
    {
        return Err(ResponseAttemptIdentityError::ResponseIdentityMismatch);
    }
    if current.action_class() != safety.action_class()
        || current.actions_digest() != safety.actions_digest()
        || current.actions_digest_profile() != safety.actions_digest_profile()
        || current.jurisdiction() != safety.jurisdiction()
    {
        return Err(ResponseAttemptIdentityError::ResponseActionMismatch);
    }
    if current.executor_authority_ref() != safety.executor_authority_ref() {
        return Err(ResponseAttemptIdentityError::ExecutorAuthorityMismatch);
    }
    Ok(())
}

/// Stable key for the exact selected effect. It intentionally excludes current
/// executor/safety generations and dynamic evidence horizons.
fn effect_identity(safety: &QualifiedResponseEffectSafety) -> Digest32 {
    let mut hasher = blake3::Hasher::new();
    hasher.update(DOMAIN_EFFECT);
    frame(&mut hasher, PROTOCOL_VERSION.as_bytes());
    frame(&mut hasher, EFFECT_IDENTITY_PROFILE.as_bytes());
    frame(&mut hasher, safety.proposal_id().as_bytes());
    frame(&mut hasher, safety.proposal_digest().as_bytes());
    frame(&mut hasher, safety.decision_id().as_bytes());
    frame(&mut hasher, safety.option_id().as_bytes());
    frame(&mut hasher, safety.action_class().as_bytes());
    frame(&mut hasher, &safety.actions_digest().0);
    frame(&mut hasher, safety.actions_digest_profile().as_bytes());
    frame(&mut hasher, safety.adapter_profile().as_bytes());
    Digest32(*hasher.finalize().as_bytes())
}

fn attempt_identity(
    effect_identity: Digest32,
    current_executor_identity: Digest32,
    safety_identity: Digest32,
    nonce: &[u8; 32],
    attempt_ref: &str,
) -> Digest32 {
    let mut hasher = blake3::Hasher::new();
    hasher.update(DOMAIN_ATTEMPT);
    frame(&mut hasher, PROTOCOL_VERSION.as_bytes());
    frame(&mut hasher, ATTEMPT_IDENTITY_PROFILE.as_bytes());
    frame(&mut hasher, &effect_identity.0);
    frame(&mut hasher, EFFECT_IDENTITY_PROFILE.as_bytes());
    frame(&mut hasher, &current_executor_identity.0);
    frame(&mut hasher, &safety_identity.0);
    frame(&mut hasher, nonce);
    frame(&mut hasher, attempt_ref.as_bytes());
    Digest32(*hasher.finalize().as_bytes())
}

fn evidence_identity(
    attempt_identity: Digest32,
    current_evidence: Digest32,
    safety_evidence: Digest32,
    prepared_at_ms: u64,
    valid_until_ms: u64,
) -> Digest32 {
    let mut hasher = blake3::Hasher::new();
    hasher.update(DOMAIN_EVIDENCE);
    frame(&mut hasher, EVIDENCE_PROFILE.as_bytes());
    frame(&mut hasher, &attempt_identity.0);
    frame(&mut hasher, &current_evidence.0);
    frame(&mut hasher, &safety_evidence.0);
    frame(&mut hasher, &prepared_at_ms.to_le_bytes());
    frame(&mut hasher, &valid_until_ms.to_le_bytes());
    Digest32(*hasher.finalize().as_bytes())
}

fn require_ref(value: &str) -> Result<(), ResponseAttemptIdentityError> {
    if value.trim().is_empty() || value.len() > MAX_REF_BYTES {
        Err(ResponseAttemptIdentityError::InvalidAttemptReference)
    } else {
        Ok(())
    }
}

fn frame(hasher: &mut blake3::Hasher, bytes: &[u8]) {
    hasher.update(&(bytes.len() as u64).to_le_bytes());
    hasher.update(bytes);
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub enum ResponseAttemptIdentityError {
    InvalidPreparationTime,
    ZeroAttemptNonce,
    InvalidAttemptReference,
    UpstreamQualificationExpired,
    ResponseSafetyIdentityMismatch,
    PendingAuthoritySubjects,
    ResponseIdentityMismatch,
    ResponseActionMismatch,
    ExecutorAuthorityMismatch,
    CoordinatorSubject(String),
    ZeroAttemptLease,
    AttemptLeaseOverflow,
    NoUsableAttemptWindow,
}

impl fmt::Display for ResponseAttemptIdentityError {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::InvalidPreparationTime => write!(f, "attempt preparation time must be non-zero"),
            Self::ZeroAttemptNonce => write!(f, "attempt nonce must not be zero"),
            Self::InvalidAttemptReference => write!(f, "invalid attempt reference"),
            Self::UpstreamQualificationExpired => write!(f, "upstream response qualification is not live"),
            Self::ResponseSafetyIdentityMismatch => write!(f, "current executor was bound to another response-safety identity"),
            Self::PendingAuthoritySubjects => write!(f, "response still has unresolved declared authority subjects"),
            Self::ResponseIdentityMismatch => write!(f, "response/current-executor identity fields differ"),
            Self::ResponseActionMismatch => write!(f, "response/current-executor action fields differ"),
            Self::ExecutorAuthorityMismatch => write!(f, "response/current-executor authority references differ"),
            Self::CoordinatorSubject(error) => write!(f, "invalid coordinator admission subject: {error}"),
            Self::ZeroAttemptLease => write!(f, "effect-safety policy permits no attempt lease"),
            Self::AttemptLeaseOverflow => write!(f, "attempt lease horizon overflowed"),
            Self::NoUsableAttemptWindow => write!(f, "no overlapping attempt evidence window remains"),
        }
    }
}

impl std::error::Error for ResponseAttemptIdentityError {}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn effect_identity_source_excludes_authority_generations_and_time() {
        let source = include_str!("lib.rs");
        let body = source
            .split("fn effect_identity(", 2)
            .nth(1)
            .unwrap()
            .split("fn attempt_identity(", 2)
            .next()
            .unwrap();
        for forbidden in [
            "executor_authority_ref",
            "qualification_digest",
            "evidence_digest",
            "verified_at_ms",
            "valid_until_ms",
            "effect_safety_qualification_digest",
        ] {
            assert!(!body.contains(forbidden), "{forbidden}");
        }
        for required in [
            "proposal_digest()",
            "decision_id()",
            "option_id()",
            "actions_digest()",
            "adapter_profile()",
        ] {
            assert!(body.contains(required), "{required}");
        }
    }

    #[test]
    fn attempt_identity_does_bind_current_authority_and_nonce() {
        let source = include_str!("lib.rs");
        let body = source
            .split("fn attempt_identity(", 2)
            .nth(1)
            .unwrap()
            .split("fn evidence_identity(", 2)
            .next()
            .unwrap();
        assert!(body.contains("current_executor_identity"));
        assert!(body.contains("safety_identity"));
        assert!(body.contains("nonce"));
        assert!(body.contains("attempt_ref"));
    }
}
