// Copyright (C) 2024-2026 Tristan Stoltz / Luminous Dynamics
// SPDX-License-Identifier: AGPL-3.0-or-later

//! A [`ZomeCallSigner`] for test/dev environments where no Launcher/Moss
//! host is present to provide `window.__HC_ZOME_CALL_SIGNER__`.
//!
//! Holochain 0.6's conductor unconditionally verifies a real Ed25519
//! signature over `sha512(bytes)` for every zome call, checked against the
//! call's `provenance` (see `handle_external_zome_call` /
//! `is_valid_signature` upstream in `holochain`'s `conductor.rs` /
//! `zome_call_signature_verification.rs`). A bare browser has no access to
//! a cell's own lair-held private key, so it can never sign as the cell's
//! real agent directly.
//!
//! Instead, following the pattern in
//! `holochain_client::AdminWebsocket::authorize_signing_credentials` (the
//! official Rust reference client), a throwaway Ed25519 keypair is
//! generated by a TRUSTED BROKER with admin-interface access, registered as
//! an `Assigned` capability grant (secret + assignee list) on the cell's
//! own source chain via `AdminRequest::GrantZomeCallCapability`, and the
//! resulting private key handed to the browser. This signer then uses that
//! GRANTED key as `provenance` in place of the cell's own agent key — the
//! zome still sees the CELL's real agent as the on-chain author regardless,
//! since capability delegation authorizes the call without changing
//! authorship (see `CapGrant::is_valid` upstream).
//!
//! See `scripts/live-browser-proof/issue-signing-credentials.mjs` for the
//! reference broker implementation (grant-issuing must happen from a
//! trusted context with admin-interface access — never expose the raw
//! admin interface to a real internet-facing browser page; in production
//! this belongs behind a small server endpoint, matching the existing
//! `/api/token` pattern in `apps/leptos/src/holochain.rs`).
//!
//! This is a distinct, separately-scoped key from the app-level hybrid-PQC
//! identity/message keys used for the V2 mail envelope (X25519+ML-KEM-768
//! KEM, dual Holochain-agent+ML-DSA-65 signatures) — it authorizes a call
//! at the Holochain transport layer, underneath that envelope, and cannot
//! itself be a PQC/hybrid scheme because the conductor's own verification
//! is hard-coded to plain Ed25519.
//!
//! Not wired into [`crate::transport::HolochainTransport::call_zome`]
//! automatically. Install via
//! `transport.set_zome_call_signer(AdminGrantedSigner::new(credentials))` —
//! a drop-in alternative to [`crate::browser::HostZomeCallSigner`] once
//! `call_zome()` consults the installed signer.

use std::future::Future;
use std::pin::Pin;

use ed25519_dalek::{Signer, SigningKey};
use sha2::{Digest, Sha512};

use crate::error::ClientError;
use crate::types::{SignedZomeCall, ZomeCallSigner, ZomeCallToSign};

/// A browser-held Ed25519 keypair authorized, via a capability grant issued
/// by a trusted broker, to sign zome calls on behalf of a cell.
#[derive(Debug, Clone)]
pub struct SigningCredentials {
    /// Wire-format (39-byte) `AgentPubKey` for the granted signing key —
    /// used as `provenance` in every zome call, in place of the cell's own
    /// agent key.
    pub signing_agent_key: Vec<u8>,
    /// Raw 32-byte Ed25519 private key seed for the granted signing key.
    pub private_key: [u8; 32],
    /// The capability secret the grant was created with (64 bytes).
    pub cap_secret: Vec<u8>,
}

/// Fields Holochain signs for zome-call authorization — matches
/// `holochain_zome_types::zome_io::ZomeCallParams` field-for-field (map
/// encoded via `to_vec_named`, so declaration order doesn't need to match
/// the real struct's, but field names/semantics must). Every raw-bytes
/// field uses `serde_bytes` to force genuine MessagePack Bin encoding,
/// matching what the real conductor's `holo_hash`/`ExternIO`/
/// `Nonce256Bits` types (themselves `serde_bytes`-annotated) expect —
/// live-verified against a real conductor for the adjacent `app_info`
/// path, where sending plain seq-encoded arrays instead was NOT the
/// problem, but this struct plays it safe rather than re-deriving that
/// finding for a request the conductor cryptographically hashes and
/// verifies (a mismatch here would silently produce a signature over the
/// wrong bytes rather than a clean deserialize error).
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
struct ZomeCallParamsWire {
    provenance: serde_bytes::ByteBuf,
    cell_id: (serde_bytes::ByteBuf, serde_bytes::ByteBuf),
    zome_name: String,
    fn_name: String,
    cap_secret: Option<serde_bytes::ByteBuf>,
    payload: serde_bytes::ByteBuf,
    nonce: serde_bytes::ByteBuf,
    expires_at: i64,
}

/// A [`ZomeCallSigner`] that signs with a broker-granted keypair instead of
/// delegating to a host environment.
#[derive(Clone)]
pub struct AdminGrantedSigner {
    credentials: SigningCredentials,
}

impl AdminGrantedSigner {
    pub fn new(credentials: SigningCredentials) -> Self {
        Self { credentials }
    }
}

impl ZomeCallSigner for AdminGrantedSigner {
    fn sign_zome_call(
        &self,
        request: ZomeCallToSign,
    ) -> Pin<Box<dyn Future<Output = Result<SignedZomeCall, ClientError>>>> {
        let credentials = self.credentials.clone();
        Box::pin(async move {
            let params = ZomeCallParamsWire {
                provenance: serde_bytes::ByteBuf::from(credentials.signing_agent_key),
                cell_id: (
                    serde_bytes::ByteBuf::from(request.cell_id.0),
                    serde_bytes::ByteBuf::from(request.cell_id.1),
                ),
                zome_name: request.zome_name,
                fn_name: request.fn_name,
                cap_secret: Some(serde_bytes::ByteBuf::from(credentials.cap_secret)),
                payload: serde_bytes::ByteBuf::from(request.payload),
                nonce: serde_bytes::ByteBuf::from(request.nonce),
                expires_at: request.expires_at as i64,
            };

            let bytes = rmp_serde::to_vec_named(&params)
                .map_err(|e| ClientError::SerializationError(e.to_string()))?;

            // The conductor verifies the signature against sha512(bytes),
            // NOT the raw bytes directly — see is_valid_signature upstream.
            let hash = Sha512::digest(&bytes);
            let signing_key = SigningKey::from_bytes(&credentials.private_key);
            let signature = signing_key.sign(&hash);

            SignedZomeCall::new(bytes, signature.to_bytes().to_vec())
        })
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn test_credentials() -> SigningCredentials {
        // A real Ed25519 seed (arbitrary but fixed for reproducibility) —
        // not a real conductor-granted key, just enough to exercise the
        // signing math end to end.
        SigningCredentials {
            signing_agent_key: vec![0x84, 0x20, 0x24]
                .into_iter()
                .chain(vec![7u8; 36])
                .collect(),
            private_key: [9u8; 32],
            cap_secret: vec![3u8; 64],
        }
    }

    #[tokio::test]
    async fn signs_and_verifies_with_the_granted_key() {
        let creds = test_credentials();
        let public_key = SigningKey::from_bytes(&creds.private_key).verifying_key();
        let signer = AdminGrantedSigner::new(creds);

        let request = ZomeCallToSign {
            cell_id: (vec![1u8; 39], vec![2u8; 39]),
            zome_name: "mail_messages".into(),
            fn_name: "get_inbox".into(),
            payload: rmp_serde::to_vec_named(&()).unwrap(),
            nonce: vec![5u8; 32],
            expires_at: 1_711_900_800_000_000,
        };

        let signed = signer.sign_zome_call(request).await.unwrap();

        // Re-derive what the conductor does: hash the bytes, verify against
        // the granted public key.
        let hash = Sha512::digest(signed.bytes());
        let signature = ed25519_dalek::Signature::from_slice(signed.signature()).unwrap();
        assert!(public_key.verify_strict(&hash, &signature).is_ok());

        // The signed bytes must decode back to the exact params we signed.
        let decoded: ZomeCallParamsWire = rmp_serde::from_slice(signed.bytes()).unwrap();
        assert_eq!(decoded.zome_name, "mail_messages");
        assert_eq!(decoded.fn_name, "get_inbox");
        assert_eq!(decoded.cap_secret.unwrap().into_vec(), vec![3u8; 64]);
    }

    #[tokio::test]
    async fn different_payloads_produce_different_signatures() {
        let creds = test_credentials();
        let signer = AdminGrantedSigner::new(creds);

        let base_request = |fn_name: &str| ZomeCallToSign {
            cell_id: (vec![1u8; 39], vec![2u8; 39]),
            zome_name: "mail_messages".into(),
            fn_name: fn_name.into(),
            payload: rmp_serde::to_vec_named(&()).unwrap(),
            nonce: vec![5u8; 32],
            expires_at: 1_711_900_800_000_000,
        };

        let a = signer
            .sign_zome_call(base_request("get_inbox"))
            .await
            .unwrap();
        let b = signer
            .sign_zome_call(base_request("get_outbox"))
            .await
            .unwrap();
        assert_ne!(a.signature(), b.signature());
    }
}
