[package]
name = "manufacturing_execution"
version = "0.1.0"
edition = "2024"
license.workspace = true

[dependencies]
hdk = { workspace = true }
manufacturing_execution_integrity = { path = "../integrity" }
serde = { workspace = true }
serde_json = { workspace = true }

[lib]
crate-type = ["cdylib", "rlib"]

[lints]
workspace = true
