[package]
name = "content_fabric_integrity"
version.workspace = true
edition.workspace = true
license.workspace = true

[lib]
crate-type = ["cdylib", "rlib"]
name = "content_fabric_integrity"

[dependencies]
hdi = { workspace = true }
serde = { workspace = true }
holochain_serialized_bytes = { workspace = true }
hex = { workspace = true }
ed25519-dalek = { workspace = true }
