// Copyright (C) 2024-2026 Tristan Stoltz / Luminous Dynamics
// SPDX-License-Identifier: AGPL-3.0-or-later
// Commercial licensing: see COMMERCIAL_LICENSE.md at repository root

//! Pure local-calendar recurrence enumeration for Hearth Care.
//!
//! This layer emits the canonical original local starts generated by the typed
//! recurrence rule. It performs no timezone lookup, DST resolution, exception
//! filtering, override application, assignment logic, or DHT writes.

use hearth_care_recurrence::{
    CareRecurrenceSpec, LocalDate, LocalDateTime, MonthlySelector, RecurrenceEnd,
    RecurrencePattern, Weekday,
};

pub const MAX_LOCAL_SCAN_DAYS: i64 = 3_660;
pub const MAX_LOCAL_OUTPUT: u32 = 10_000;

#[derive(Debug, Clone, PartialEq, Eq)]
pub enum EnumerationError {
    InvalidContract(String),
    InvalidBounds,
    BoundsTooWide { days: i64, max_days: i64 },
    OutputLimitExceeded(u32),
    DateOutOfRange,
}

impl std::fmt::Display for EnumerationError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "{self:?}")
    }
}
impl std::error::Error for EnumerationError {}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct LocalExpansionBounds {
    pub start_inclusive: LocalDate,
    pub end_exclusive: LocalDate,
    pub max_instances: u32,
}

impl LocalExpansionBounds {
    pub fn validate(&self) -> Result<(), EnumerationError> {
        self.start_inclusive
            .validate()
            .map_err(contract_error)?;
        self.end_exclusive
            .validate()
            .map_err(contract_error)?;
        let start = ordinal(&self.start_inclusive)?;
        let end = ordinal(&self.end_exclusive)?;
        if end <= start {
            return Err(EnumerationError::InvalidBounds);
        }
        let days = end - start;
        if days > MAX_LOCAL_SCAN_DAYS {
            return Err(EnumerationError::BoundsTooWide {
                days,
                max_days: MAX_LOCAL_SCAN_DAYS,
            });
        }
        if self.max_instances == 0 || self.max_instances > MAX_LOCAL_OUTPUT {
            return Err(EnumerationError::OutputLimitExceeded(self.max_instances));
        }
        Ok(())
    }
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct LocalRecurrenceSeries {
    /// Original recurrence starts before EXDATE/cancel/move transformations.
    pub original_starts: Vec<LocalDateTime>,
}

/// Enumerate original local recurrence starts within a bounded local-date range.
///
/// Schema-v1 semantics:
/// - Monday anchors multi-week intervals (RFC 5545 default WKST=MO).
/// - Invalid calendar dates are skipped, not clamped.
/// - COUNT counts generated original recurrence instances starting with DTSTART.
/// - Exclusions/overrides do not extend a COUNT-limited series.
/// - UNTIL is inclusive by local date.
pub fn enumerate_original_starts(
    spec: &CareRecurrenceSpec,
    bounds: &LocalExpansionBounds,
) -> Result<LocalRecurrenceSeries, EnumerationError> {
    spec.validate().map_err(contract_error)?;
    bounds.validate()?;

    let starts = match &spec.end {
        RecurrenceEnd::Count(count) => enumerate_count_limited(spec, bounds, *count)?,
        RecurrenceEnd::Never | RecurrenceEnd::UntilLocalDate(_) => enumerate_bounded(spec, bounds)?,
    };
    if starts.len() > bounds.max_instances as usize {
        return Err(EnumerationError::OutputLimitExceeded(
            starts.len().min(u32::MAX as usize) as u32,
        ));
    }
    Ok(LocalRecurrenceSeries {
        original_starts: starts,
    })
}

fn enumerate_bounded(
    spec: &CareRecurrenceSpec,
    bounds: &LocalExpansionBounds,
) -> Result<Vec<LocalDateTime>, EnumerationError> {
    let start_ordinal = ordinal(&spec.starts_local.date)?;
    let mut current_ordinal = ordinal(&bounds.start_inclusive)?.max(start_ordinal);
    let end_ordinal = ordinal(&bounds.end_exclusive)?;
    let mut out = Vec::new();

    while current_ordinal < end_ordinal {
        let date = date_from_ordinal(current_ordinal)?;
        if let RecurrenceEnd::UntilLocalDate(until) = &spec.end {
            if &date > until {
                break;
            }
        }
        if pattern_matches(&spec.pattern, &spec.starts_local.date, &date)? {
            let value = LocalDateTime {
                date,
                time: spec.starts_local.time.clone(),
            };
            if &value >= &spec.starts_local {
                out.push(value);
                if out.len() > bounds.max_instances as usize {
                    return Err(EnumerationError::OutputLimitExceeded(
                        out.len().min(u32::MAX as usize) as u32,
                    ));
                }
            }
        }
        current_ordinal += 1;
    }
    Ok(out)
}

fn enumerate_count_limited(
    spec: &CareRecurrenceSpec,
    bounds: &LocalExpansionBounds,
    count: u32,
) -> Result<Vec<LocalDateTime>, EnumerationError> {
    let all = match &spec.pattern {
        RecurrencePattern::Once => vec![spec.starts_local.clone()],
        RecurrencePattern::Daily { interval } => enumerate_daily_count(spec, *interval, count)?,
        RecurrencePattern::Weekly { interval, weekdays } => {
            enumerate_weekly_count(spec, *interval, weekdays, count)?
        }
        RecurrencePattern::Monthly { interval, selector } => {
            enumerate_monthly_count(spec, *interval, selector, count)?
        }
        RecurrencePattern::Yearly { interval, month, day } => {
            enumerate_yearly_count(spec, *interval, *month, *day, count)?
        }
    };
    let start_bound = ordinal(&bounds.start_inclusive)?;
    let end_bound = ordinal(&bounds.end_exclusive)?;
    let mut filtered = Vec::new();
    for value in all {
        let day = ordinal(&value.date)?;
        if day >= start_bound && day < end_bound {
            filtered.push(value);
        }
    }
    Ok(filtered)
}

fn enumerate_daily_count(
    spec: &CareRecurrenceSpec,
    interval: u16,
    count: u32,
) -> Result<Vec<LocalDateTime>, EnumerationError> {
    let start = ordinal(&spec.starts_local.date)?;
    let mut out = Vec::with_capacity(count as usize);
    for index in 0..count {
        let delta = i64::from(index).saturating_mul(i64::from(interval));
        let date = date_from_ordinal(start.saturating_add(delta))?;
        out.push(LocalDateTime {
            date,
            time: spec.starts_local.time.clone(),
        });
    }
    Ok(out)
}

fn enumerate_weekly_count(
    spec: &CareRecurrenceSpec,
    interval: u16,
    weekdays: &[Weekday],
    count: u32,
) -> Result<Vec<LocalDateTime>, EnumerationError> {
    let start_day = ordinal(&spec.starts_local.date)?;
    let monday_anchor = start_day - i64::from(weekday_index(weekday(&spec.starts_local.date)?));
    let mut out = Vec::with_capacity(count as usize);
    let mut period = 0_i64;

    while out.len() < count as usize {
        let week_base = monday_anchor
            .checked_add(period.saturating_mul(i64::from(interval)).saturating_mul(7))
            .ok_or(EnumerationError::DateOutOfRange)?;
        for day_of_week in weekdays {
            let candidate = week_base + i64::from(weekday_index(*day_of_week));
            if candidate < start_day {
                continue;
            }
            let date = match date_from_ordinal(candidate) {
                Ok(value) => value,
                Err(EnumerationError::DateOutOfRange) => return Ok(out),
                Err(error) => return Err(error),
            };
            out.push(LocalDateTime {
                date,
                time: spec.starts_local.time.clone(),
            });
            if out.len() == count as usize {
                break;
            }
        }
        period = period.saturating_add(1);
        if period > 1_000_000 {
            return Err(EnumerationError::DateOutOfRange);
        }
    }
    Ok(out)
}

fn enumerate_monthly_count(
    spec: &CareRecurrenceSpec,
    interval: u16,
    selector: &MonthlySelector,
    count: u32,
) -> Result<Vec<LocalDateTime>, EnumerationError> {
    let start_month = month_index(spec.starts_local.date.year, spec.starts_local.date.month);
    let mut out = Vec::with_capacity(count as usize);
    let mut period = 0_i64;

    while out.len() < count as usize {
        let index = start_month
            .checked_add(period.saturating_mul(i64::from(interval)))
            .ok_or(EnumerationError::DateOutOfRange)?;
        let Some((year, month)) = month_from_index(index) else {
            break;
        };
        if let Some(date) = monthly_candidate(year, month, selector)? {
            let value = LocalDateTime {
                date,
                time: spec.starts_local.time.clone(),
            };
            if &value >= &spec.starts_local {
                out.push(value);
            }
        }
        period = period.saturating_add(1);
        if period > 100_000 {
            return Err(EnumerationError::DateOutOfRange);
        }
    }
    Ok(out)
}

fn enumerate_yearly_count(
    spec: &CareRecurrenceSpec,
    interval: u16,
    month: u8,
    day: u8,
    count: u32,
) -> Result<Vec<LocalDateTime>, EnumerationError> {
    let mut out = Vec::with_capacity(count as usize);
    let mut period = 0_i64;
    while out.len() < count as usize {
        let year_i64 = i64::from(spec.starts_local.date.year)
            .saturating_add(period.saturating_mul(i64::from(interval)));
        let Ok(year) = i32::try_from(year_i64) else {
            break;
        };
        if !(1900..=9999).contains(&year) {
            break;
        }
        if day <= days_in_month(year, month) {
            let value = LocalDateTime {
                date: LocalDate { year, month, day },
                time: spec.starts_local.time.clone(),
            };
            if &value >= &spec.starts_local {
                out.push(value);
            }
        }
        period = period.saturating_add(1);
        if period > 10_000 {
            break;
        }
    }
    Ok(out)
}

fn pattern_matches(
    pattern: &RecurrencePattern,
    start: &LocalDate,
    date: &LocalDate,
) -> Result<bool, EnumerationError> {
    if date < start {
        return Ok(false);
    }
    let start_day = ordinal(start)?;
    let day = ordinal(date)?;
    Ok(match pattern {
        RecurrencePattern::Once => date == start,
        RecurrencePattern::Daily { interval } => {
            (day - start_day) % i64::from(*interval) == 0
        }
        RecurrencePattern::Weekly { interval, weekdays } => {
            let monday_anchor = start_day - i64::from(weekday_index(weekday(start)?));
            let week = (day - monday_anchor) / 7;
            week >= 0
                && week % i64::from(*interval) == 0
                && weekdays.binary_search(&weekday(date)?).is_ok()
        }
        RecurrencePattern::Monthly { interval, selector } => {
            let months = month_index(date.year, date.month) - month_index(start.year, start.month);
            months >= 0
                && months % i64::from(*interval) == 0
                && monthly_selector_matches(selector, date)?
        }
        RecurrencePattern::Yearly { interval, month, day } => {
            let years = i64::from(date.year) - i64::from(start.year);
            years >= 0
                && years % i64::from(*interval) == 0
                && date.month == *month
                && date.day == *day
        }
    })
}

fn monthly_candidate(
    year: i32,
    month: u8,
    selector: &MonthlySelector,
) -> Result<Option<LocalDate>, EnumerationError> {
    let max = days_in_month(year, month);
    let date = match selector {
        MonthlySelector::DayOfMonth(day) => {
            if *day > max {
                return Ok(None);
            }
            LocalDate {
                year,
                month,
                day: *day,
            }
        }
        MonthlySelector::NthWeekday { ordinal, weekday: target } => {
            let day = if *ordinal > 0 {
                let first = LocalDate { year, month, day: 1 };
                let delta = (7 + i16::from(weekday_index(*target))
                    - i16::from(weekday_index(weekday(&first)?)))
                    % 7;
                1_i16 + delta + 7 * (i16::from(*ordinal) - 1)
            } else {
                let last = LocalDate {
                    year,
                    month,
                    day: max,
                };
                let delta = (7 + i16::from(weekday_index(weekday(&last)?))
                    - i16::from(weekday_index(*target)))
                    % 7;
                i16::from(max) - delta - 7 * (i16::from(-*ordinal) - 1)
            };
            if day < 1 || day > i16::from(max) {
                return Ok(None);
            }
            LocalDate {
                year,
                month,
                day: u8::try_from(day).map_err(|_| EnumerationError::DateOutOfRange)?,
            }
        }
    };
    Ok(Some(date))
}

fn monthly_selector_matches(
    selector: &MonthlySelector,
    date: &LocalDate,
) -> Result<bool, EnumerationError> {
    Ok(monthly_candidate(date.year, date.month, selector)?.as_ref() == Some(date))
}

fn weekday(date: &LocalDate) -> Result<Weekday, EnumerationError> {
    date.weekday().map_err(contract_error)
}

fn weekday_index(day: Weekday) -> u8 {
    match day {
        Weekday::Monday => 0,
        Weekday::Tuesday => 1,
        Weekday::Wednesday => 2,
        Weekday::Thursday => 3,
        Weekday::Friday => 4,
        Weekday::Saturday => 5,
        Weekday::Sunday => 6,
    }
}

fn month_index(year: i32, month: u8) -> i64 {
    i64::from(year) * 12 + i64::from(month) - 1
}

fn month_from_index(index: i64) -> Option<(i32, u8)> {
    let year = index.div_euclid(12);
    let month_zero = index.rem_euclid(12);
    let year = i32::try_from(year).ok()?;
    if !(1900..=9999).contains(&year) {
        return None;
    }
    Some((year, u8::try_from(month_zero + 1).ok()?))
}

fn ordinal(date: &LocalDate) -> Result<i64, EnumerationError> {
    date.validate().map_err(contract_error)?;
    let mut days = days_before_year(date.year);
    for month in 1..date.month {
        days += i64::from(days_in_month(date.year, month));
    }
    Ok(days + i64::from(date.day) - 1)
}

fn date_from_ordinal(value: i64) -> Result<LocalDate, EnumerationError> {
    let min = days_before_year(1900);
    let max_exclusive = days_before_year(10_000);
    if value < min || value >= max_exclusive {
        return Err(EnumerationError::DateOutOfRange);
    }

    let mut low = 1900_i32;
    let mut high = 10_000_i32;
    while low + 1 < high {
        let mid = low + (high - low) / 2;
        if days_before_year(mid) <= value {
            low = mid;
        } else {
            high = mid;
        }
    }
    let year = low;
    let mut day_of_year = value - days_before_year(year);
    let mut month = 1_u8;
    loop {
        let len = i64::from(days_in_month(year, month));
        if day_of_year < len {
            break;
        }
        day_of_year -= len;
        month += 1;
    }
    let date = LocalDate {
        year,
        month,
        day: u8::try_from(day_of_year + 1).map_err(|_| EnumerationError::DateOutOfRange)?,
    };
    date.validate().map_err(|_| EnumerationError::DateOutOfRange)?;
    Ok(date)
}

fn days_before_year(year: i32) -> i64 {
    let y = i64::from(year) - 1;
    365 * y + y / 4 - y / 100 + y / 400
}

fn is_leap_year(year: i32) -> bool {
    year % 4 == 0 && (year % 100 != 0 || year % 400 == 0)
}

fn days_in_month(year: i32, month: u8) -> u8 {
    match month {
        1 | 3 | 5 | 7 | 8 | 10 | 12 => 31,
        4 | 6 | 9 | 11 => 30,
        2 if is_leap_year(year) => 29,
        2 => 28,
        _ => 0,
    }
}

fn contract_error(error: impl std::fmt::Display) -> EnumerationError {
    EnumerationError::InvalidContract(error.to_string())
}

#[cfg(test)]
mod tests {
    use super::*;
    use hearth_care_recurrence::{
        CivilTimePolicy, LocalTime, MissedOccurrencePolicy, OccurrenceOverride, OverrideAction,
        RecurrenceEnd, TimeZoneId, RECURRENCE_SCHEMA_VERSION,
    };

    fn date(year: i32, month: u8, day: u8) -> LocalDate {
        LocalDate { year, month, day }
    }

    fn local(year: i32, month: u8, day: u8, hour: u8) -> LocalDateTime {
        LocalDateTime {
            date: date(year, month, day),
            time: LocalTime {
                hour,
                minute: 0,
                second: 0,
            },
        }
    }

    fn spec(
        pattern: RecurrencePattern,
        end: RecurrenceEnd,
        starts: LocalDateTime,
    ) -> CareRecurrenceSpec {
        CareRecurrenceSpec {
            schema_version: RECURRENCE_SCHEMA_VERSION,
            schedule_ref: "schedule:1".into(),
            recurrence_state_ref: "recurrence:1".into(),
            timezone: TimeZoneId("Africa/Johannesburg".into()),
            starts_local: starts,
            duration_minutes: 30,
            pattern,
            end,
            civil_time_policy: CivilTimePolicy::default(),
            missed_policy: MissedOccurrencePolicy::SurfaceForReview,
            exclusions: Vec::new(),
            overrides: Vec::new(),
        }
    }

    fn bounds(start: LocalDate, end: LocalDate) -> LocalExpansionBounds {
        LocalExpansionBounds {
            start_inclusive: start,
            end_exclusive: end,
            max_instances: 100,
        }
    }

    #[test]
    fn daily_interval_is_anchored_to_dtstart() {
        let value = spec(
            RecurrencePattern::Daily { interval: 2 },
            RecurrenceEnd::Never,
            local(2026, 9, 21, 18),
        );
        let result = enumerate_original_starts(
            &value,
            &bounds(date(2026, 9, 21), date(2026, 9, 28)),
        )
        .unwrap();
        assert_eq!(
            result.original_starts,
            vec![
                local(2026, 9, 21, 18),
                local(2026, 9, 23, 18),
                local(2026, 9, 25, 18),
                local(2026, 9, 27, 18),
            ]
        );
    }

    #[test]
    fn multiweek_semantics_use_monday_anchor() {
        let value = spec(
            RecurrencePattern::Weekly {
                interval: 2,
                weekdays: vec![Weekday::Tuesday, Weekday::Sunday],
            },
            RecurrenceEnd::Count(4),
            local(1997, 8, 5, 9),
        );
        let result = enumerate_original_starts(
            &value,
            &bounds(date(1997, 8, 1), date(1997, 9, 1)),
        )
        .unwrap();
        assert_eq!(
            result
                .original_starts
                .iter()
                .map(|value| value.date.clone())
                .collect::<Vec<_>>(),
            vec![
                date(1997, 8, 5),
                date(1997, 8, 10),
                date(1997, 8, 19),
                date(1997, 8, 24),
            ]
        );
    }

    #[test]
    fn monthly_day_31_skips_invalid_dates_and_does_not_count_them() {
        let value = spec(
            RecurrencePattern::Monthly {
                interval: 1,
                selector: MonthlySelector::DayOfMonth(31),
            },
            RecurrenceEnd::Count(3),
            local(2026, 1, 31, 9),
        );
        let result = enumerate_original_starts(
            &value,
            &bounds(date(2026, 1, 1), date(2026, 7, 1)),
        )
        .unwrap();
        assert_eq!(
            result
                .original_starts
                .iter()
                .map(|value| value.date.clone())
                .collect::<Vec<_>>(),
            vec![date(2026, 1, 31), date(2026, 3, 31), date(2026, 5, 31)]
        );
    }

    #[test]
    fn yearly_feb_29_skips_non_leap_years() {
        let value = spec(
            RecurrencePattern::Yearly {
                interval: 1,
                month: 2,
                day: 29,
            },
            RecurrenceEnd::Count(3),
            local(2024, 2, 29, 8),
        );
        let result = enumerate_original_starts(
            &value,
            &bounds(date(2024, 1, 1), date(2033, 1, 1)),
        )
        .unwrap();
        assert_eq!(
            result
                .original_starts
                .iter()
                .map(|value| value.date.clone())
                .collect::<Vec<_>>(),
            vec![date(2024, 2, 29), date(2028, 2, 29), date(2032, 2, 29)]
        );
    }

    #[test]
    fn count_is_before_exclusions_so_cancel_does_not_extend_series() {
        let mut value = spec(
            RecurrencePattern::Daily { interval: 1 },
            RecurrenceEnd::Count(2),
            local(2026, 9, 21, 18),
        );
        value.exclusions.push(local(2026, 9, 21, 18));
        value.overrides = Vec::<OccurrenceOverride>::new();
        let result = enumerate_original_starts(
            &value,
            &bounds(date(2026, 9, 21), date(2026, 9, 25)),
        )
        .unwrap();
        assert_eq!(
            result.original_starts,
            vec![local(2026, 9, 21, 18), local(2026, 9, 22, 18)]
        );
    }

    #[test]
    fn moved_override_does_not_change_original_series_identity() {
        let mut value = spec(
            RecurrencePattern::Daily { interval: 1 },
            RecurrenceEnd::Count(2),
            local(2026, 9, 21, 18),
        );
        value.overrides.push(OccurrenceOverride {
            original_start_local: local(2026, 9, 21, 18),
            action: OverrideAction::Move {
                new_start_local: local(2026, 9, 21, 20),
                duration_minutes: None,
            },
        });
        let result = enumerate_original_starts(
            &value,
            &bounds(date(2026, 9, 21), date(2026, 9, 24)),
        )
        .unwrap();
        assert_eq!(result.original_starts[0], local(2026, 9, 21, 18));
    }

    #[test]
    fn until_is_inclusive() {
        let value = spec(
            RecurrencePattern::Daily { interval: 1 },
            RecurrenceEnd::UntilLocalDate(date(2026, 9, 23)),
            local(2026, 9, 21, 18),
        );
        let result = enumerate_original_starts(
            &value,
            &bounds(date(2026, 9, 20), date(2026, 9, 30)),
        )
        .unwrap();
        assert_eq!(result.original_starts.len(), 3);
        assert_eq!(result.original_starts[2], local(2026, 9, 23, 18));
    }

    #[test]
    fn open_ended_scan_is_bounded() {
        let value = spec(
            RecurrencePattern::Daily { interval: 1 },
            RecurrenceEnd::Never,
            local(2026, 1, 1, 0),
        );
        let error = enumerate_original_starts(
            &value,
            &LocalExpansionBounds {
                start_inclusive: date(2026, 1, 1),
                end_exclusive: date(2040, 1, 1),
                max_instances: 10_000,
            },
        )
        .unwrap_err();
        assert!(matches!(error, EnumerationError::BoundsTooWide { .. }));
    }
}
